In [1]:
import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [ ]:
a = np.array([1,2,3,4])
b = np.array([10,28,30,40])
c = np.array([0.1,0.5,0.9,1.5])

In [ ]:
np.add(a,b)

array([11, 30, 33, 44])

In [ ]:
np.subtract(a,b)

array([ -9, -26, -27, -36])

In [ ]:
np.multiply(a,b)

array([ 10,  56,  90, 160])

In [ ]:
np.divide(a,b)

array([0.1       , 0.07142857, 0.1       , 0.1       ])

In [ ]:
np.mod(a,b)

array([1, 2, 3, 4])

In [ ]:
np.floor_divide(b,a)

array([10, 14, 10, 10])

In [ ]:
np.power(b,3)

array([ 1000, 21952, 27000, 64000])

In [ ]:
np.lcm(12,20)

np.int64(60)