In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,28,30,40])
c = np.array([0.1,0.5,0.9,1.5])

In [4]:
np.add(a,b)

array([11, 30, 33, 44])

In [5]:
np.subtract(a,b)

array([ -9, -26, -27, -36])

In [6]:
np.multiply(a,b)

array([ 10,  56,  90, 160])

In [7]:
np.divide(a,b)

array([0.1       , 0.07142857, 0.1       , 0.1       ])

In [8]:
np.mod(a,b)

array([1, 2, 3, 4])

In [10]:
np.floor_divide(b,a)

array([10, 14, 10, 10])

In [11]:
np.power(b,3)

array([ 1000, 21952, 27000, 64000])

In [12]:
np.lcm(12,20)

np.int64(60)