#### Create a NumPy array with numbers 5, 10, 15, 20 and print its type and shape.

In [1]:
import numpy as np
arr = np.array([5,10,15,20])
print(arr)
print(type(arr))
print(arr.shape)

[ 5 10 15 20]
<class 'numpy.ndarray'>
(4,)


#### 1. From Python list

In [2]:
np.array([1, 2, 3])

array([1, 2, 3])

#### 2. With all zeros

In [3]:
np.zeros((2, 3))  # 2 rows, 3 columns of 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 3. With all ones

In [4]:
np.ones((3, 2))   # 3 rows, 2 columns of 1s

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### 4. With a specific value

In [5]:
np.full((2, 2), 7)  # 2x2 filled with 7

array([[7, 7],
       [7, 7]])

#### 5. Range of numbers

In [6]:
np.arange(1, 10, 2)  # start=1, stop<10, step=2

array([1, 3, 5, 7, 9])

#### 6. Evenly spaced numbers

In [10]:
np.linspace(0, 1, 5)  # 5 points between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Coding Drill:
* Create:
  *  1.    A 3×3 array of all 9s

In [14]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

* 2. A 1D array of numbers from 20 to 30 with a step of 2

In [15]:
np.arange(20,30,3)

array([20, 23, 26, 29])