####  2️⃣ Create a NumPy array with numbers 5, 10, 15, 20 and print its type and shape.

In [2]:
import numpy as np
arr = np.array([5,10,15,20])
print(arr)
print(type(arr))
print(arr.shape)

[ 5 10 15 20]
<class 'numpy.ndarray'>
(4,)


#### 1. From Python list

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

#### 2. With all zeros

In [4]:
np.zeros((2, 3))  # 2 rows, 3 columns of 0s

array([[0., 0., 0.],
       [0., 0., 0.]])

#### 3. With all ones

In [5]:
np.ones((3, 2))   # 3 rows, 2 columns of 1s

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#### 4. With a specific value

In [6]:
np.full((2, 2), 7)  # 2x2 filled with 7

array([[7, 7],
       [7, 7]])

#### 5. Range of numbers

In [7]:
np.arange(1, 10, 2)  # start=1, stop<10, step=2

array([1, 3, 5, 7, 9])

#### 6. Evenly spaced numbers

In [8]:
np.linspace(0, 1, 5)  # 5 points between 0 and 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### Coding Drill:
* Create:
  *  1.    A 3×3 array of all 9s

In [9]:
np.full((3,3),9)

array([[9, 9, 9],
       [9, 9, 9],
       [9, 9, 9]])

* 2. A 1D array of numbers from 20 to 30 with a step of 2

In [10]:
np.arange(20,30,3)

array([20, 23, 26, 29])

### 3️⃣ Array Indexing and Slicing
   ##### Think of it like lists, but arrays can be multi-dimensional.

#### Indexing (picking single elements):

In [11]:
arr = np.array([10, 20, 30, 40])
print(arr[0])   # 10
print(arr[-1])  # 40

10
40


#### Slicing (picking ranges):

In [12]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])   # [20 30 40]
print(arr[:3])    # [10 20 30]
print(arr[::2])   # [10 30 50]

[20 30 40]
[10 20 30]
[10 30 50]


#### 2D indexing:

In [13]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat[0, 1])    # row 0, col 1 → 2
print(mat[1, :])    # all cols in row 1 → [4 5 6]
print(mat[:, 0])    # all rows in col 0 → [1 4]

2
[4 5 6]
[1 4]


#### Example 1 – Making a 2×5 matrix uaing arange() and reshape()
* reshape() -  it shapes the array as we give parameter like 2 x 4 or 3D parameter 

In [14]:
arr = np.arange(1, 11).reshape(2, 5)
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### Code drill

In [15]:
arr = np.array([[5, 6, 7], [8, 9, 10]])
print(arr[1, :2])

[8 9]


### Mini coding drill (Indexing & Slicing):

Create a 3×3 NumPy array with numbers 1–9.

Print:

The element in row 2, column 3

All elements from row 1

The first column from all rows

In [16]:
import numpy as np
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [17]:
print(arr[1][2])

6


In [18]:
print(arr[0])

[1 2 3]


In [19]:
print(arr[:, 0])

[1 4 7]


In [20]:
arr1 = np.arange(1,7).reshape(2,3)

In [21]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
print(arr1[1,1])

5


#### Now try the coding drill:

### Create an array from 50 to 65 (inclusive), reshape to 4×4, and print element at row 3, column 2.

In [25]:
arrNew1 = np.arange(50,66).reshape(4,4)

In [26]:
arrNew1

array([[50, 51, 52, 53],
       [54, 55, 56, 57],
       [58, 59, 60, 61],
       [62, 63, 64, 65]])

In [30]:
arrNew1[2,1]

np.int64(59)

### 4️⃣ Understanding Random Module in NumPy.

##### NumPy’s random module lets you create random numbers or random samples quickly.
  * 1. Initializing model weights randomly before training

In ML models (like neural networks), we have “weights” that decide how strongly inputs affect outputs.

At the start, we don’t know the right values, so we set them to random numbers (instead of all zeros — which would make the model fail to learn properly).

Why random? → Helps the model start learning in different directions instead of being stuck.

Example:

In [32]:
weights = np.random.randn(3, 3)  # 3x3 matrix of random weights
weights

array([[ 1.49192093, -0.37997005,  0.40693598],
       [ 0.99087041, -0.29102437, -0.72941424],
       [-0.3177588 ,  0.53242969,  1.02995818]])

* 2. Splitting datasets into random train/test sets

In ML, we train the model on some data (train set) and test it on unseen data (test set).

We need to pick these randomly so that our test set is unbiased.

Example:

In [38]:
data = np.arange(1, 11)
np.random.shuffle(data)  # randomize order
train, test = data[:7], data[7:]  # 70% train, 30% test
print(f"70%: train: {train},\ntest 30% test :{test}")

70%: train: [ 2  4  1  6  5  3 10],
test 30% test :[9 8 7]


* 3. Data augmentation (random noise for images)

If you have a small dataset, you can add small random changes to create more data for training.

In image classification, adding random brightness or noise helps the model generalize better.

Example:

In [43]:
image = np.ones((3, 3)) * 100  # dummy grayscale image
noise = np.random.randint(-20, 20, size=(3, 3))
augmented = image + noise
print(f" image data:\n {image} \nnoise data: \n {noise}\naugmented: \n {augmented}")

 image data:
 [[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]] 
noise data: 
 [[ 2  8 17]
 [19  7 -8]
 [-8 16 -1]]
augmented: 
 [[102. 108. 117.]
 [119. 107.  92.]
 [ 92. 116.  99.]]


* 4. Simulations (Monte Carlo simulations)

Used in finance, physics, risk analysis → run many random scenarios to estimate outcomes.

Example: Estimating stock price fluctuations or predicting weather.

Below This lets analysts see possible outcomes before making a decision.

simulated_prices = np.random.normal(100, 10, size=50)  # mean=100, std=10
print(simulated_prices)

#### 1.Random float between 0 and 1

In [47]:
print(np.random.rand(3))  # 1D array of 3 random floats

[0.97282806 0.20535657 0.67824765]


#### 2. Random 2D array

In [48]:
np.random.rand(2, 3)  # shape = (2, 3)

array([[0.11622855, 0.01987713, 0.45089983],
       [0.426453  , 0.76344776, 0.815065  ]])

#### 3. Random integers between a range

In [51]:
np.random.randint(1, 10, size=(2, 4))  # 2 rows × 4 cols

array([[9, 8, 2, 3],
       [4, 9, 1, 2]], dtype=int32)

#### 4. Random choice from a list

In [52]:
np.random.choice([10, 20, 30, 40], size=3)

array([30, 10, 10])

#### 5. Normally distributed random numbers (mean=0, std=1)

In [53]:
np.random.randn(5)

array([ 1.03270968, -2.02860382,  0.46762525, -2.18276036,  0.37603188])

### Code Drill
Task:

Create a dataset of 10 random integers between 50 and 100 (inclusive).

Randomly shuffle them.

Split into first 7 elements = train set, last 3 elements = test set.

In [64]:
np1 = np.random.randint(50,101, size =10)

In [66]:
np.random.shuffle(np1)

In [67]:
train,test = np1[:7], np1[7:]

In [68]:
print(f"70%: train: {train},\ntest 30% test :{test}")

70%: train: [56 65 65 81 85 75 65],
test 30% test :[81 63 51]


### 5️⃣ Mathematical Operations in NumPy.
* Examples

In [69]:
import numpy as np

arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

# Element-wise math
print(arr1 + arr2)  # [11 22 33]
print(arr1 - arr2)  # [ 9 18 27]
print(arr1 * arr2)  # [10 40 90]
print(arr1 / arr2)  # [10. 10. 10.]

# revise maths topics sine function and natrual log to know correctly

# Built-in math functions
print(np.sqrt(arr1))   # square root
print(np.log(arr2))    # natural log
print(np.sin(arr2))    # sine function


[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
[3.16227766 4.47213595 5.47722558]
[0.         0.69314718 1.09861229]
[0.84147098 0.90929743 0.14112001]


In [72]:
arr = np.array([2, 4, 6])
print(np.sqrt(arr))
print(np.log(arr))
print(np.sqrt(arr) + np.log(arr))

[1.41421356 2.         2.44948974]
[0.69314718 1.38629436 1.79175947]
[2.10736074 3.38629436 4.24124921]


#### Coding Drill — Normalization -  Math formula operation 

Self learn and esplore how to do basic calculations

In ML, we often normalize features to 0–1 range so all features are comparable.
Formula:
normalized = (arr - min) / (max - min)

Your task:

Create a NumPy array with values [10, 15, 20, 25, 30]

Normalize them so the smallest = 0 and largest = 1

In [73]:
arrNum = np.array([10,15,20,25,30])
arrNum

array([10, 15, 20, 25, 30])

In [76]:
mini = min(arrNum)

In [75]:
maxi = max(arrNum)

In [79]:
normalized  = (arrNum - mini) / (maxi - mini)

In [80]:
print(normalized)

[0.   0.25 0.5  0.75 1.  ]


#### 6️⃣ NumPy Array Operations

In [82]:
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

In [83]:
# Total of all elements
print(np.sum(arr))

210


In [84]:
# Average of all elements
print(np.mean(arr))

35.0


In [85]:
# Minimum and Maximum
print(np.min(arr))         
print(np.max(arr))         

10
60


In [86]:
# Standard Deviation & Variance
print(np.std(arr))       
print(np.var(arr))

17.07825127659933
291.6666666666667


In [87]:
# Column-wise mean (axis=0)
print(np.mean(arr, axis=0))

[25. 35. 45.]


In [88]:
# Row-wise sum (axis=1)
print(np.sum(arr, axis=1))

[ 60 150]


#### Coding Drill

Create a 4×3 array of random integers between 10 and 50. Then:

Find the sum for each row.

Find the mean for each column.

Find the overall standard deviation of the array.

In [91]:
arr3 = np.random.randint(10, 51, size=(4, 3))
arr3

array([[12, 12, 18],
       [10, 32, 38],
       [36, 33, 42],
       [17, 36, 29]], dtype=int32)

In [93]:
print(np.sum(arr3[0]))
print(np.sum(arr3[1]))
print(np.sum(arr3[2]))
print(np.sum(arr3[3]))

42
80
111
82


In [95]:
print(np.mean(arr3[:,0]))
print(np.mean(arr3[:,1]))
print(np.mean(arr3[:,2]))

18.75
28.25
31.75


In [96]:
print(np.std(arr3))

11.128978689289807


### 7️⃣ Array Reshaping

In [99]:
arr = np.arange(1, 13)
print()
# 1D → 2D
print(arr.reshape(3, 4))
print()
# Auto-calculate rows
print(arr.reshape(-1, 6))
print()
# 1D → 3D
print(arr.reshape(2, 2, 3))



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [100]:
arr4 = np.arange(8)

In [101]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7])

In [103]:
arr4.reshape(2,-1)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

### Code Drill
Do you want to try the reshaping coding drill now?
It’s the one where you:

Make numbers 1–24

Reshape to 4×6

Reshape to (2, 3, 4)

In [104]:
arrNew2 = np.arange(1,25)

In [105]:
print(arrNew2.reshape(4,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [107]:
print(arrNew2.reshape(2,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### 8️⃣ Random Number Generation
#### Examples : - 

In [108]:
# Reproducible random integers
np.random.seed(1)
print(np.random.randint(1, 10, size=5))

[6 9 6 1 1]


In [109]:
# Random floats between 0 and 1
print(np.random.rand(3))

[0.39658073 0.38791074 0.66974604]


In [110]:
# Random choice from list
print(np.random.choice([2, 4, 6, 8], size=2))

[4 6]


In [111]:
# Normal distribution: mean=50, std=5
print(np.random.normal(50, 5, size=4))

[47.67656838 54.30913559 36.7286901  55.76132458]


In [115]:
np.random.seed(7)
print(np.random.randint(1, 100, size=5))

[48 69 26 68 84]


### Coding Drill
Task:

Generate 8 random integers between 1 and 50 with seed=21.

Run the same code twice and check if the results are identical.

Then remove the seed line and run again to see the difference.

In [118]:
np.random.seed(21)  
nums = np.random.randint(1, 51, size=8)
print(nums)

[10 16  5 49 49 36 35 50]
