### NUMPY 

In [55]:
import numpy as np

In [56]:
array_1 = np.array([1,2,3,4])

In [57]:
type(array_1)

numpy.ndarray

In [58]:
my_mat = np.array([[12,45,32],[2323,44,22]]) 
my_mat

array([[  12,   45,   32],
       [2323,   44,   22]])

In [59]:
nested_lst = [[12,45,32],[2323,44,22]] # grabbing in a nested list
nested_lst[0][2]

32

In [60]:
# grabbing an element  in a n dimensional array
my_mat[0][1]

np.int64(45)

In [61]:
my_mat2 = np.array([[11,12,13,21],[14,15,16,22],[17,18,19,23]])
my_mat2 

array([[11, 12, 13, 21],
       [14, 15, 16, 22],
       [17, 18, 19, 23]])

In [62]:
my_mat2[-1][-2] # grabbing by -ve indexing 

np.int64(19)

### Grabbing 18 from the matrix

In [63]:
my_mat2[2][1]

np.int64(18)

In [64]:
my_mat2[2][-3]

np.int64(18)

In [65]:
my_mat2[-1][1]

np.int64(18)

In [66]:
my_mat2[-1][-3]

np.int64(18)

#### Grabbing by column

In [ ]:
my_mat2[:,0] 

array([11, 14, 17])

#### Assiging values

In [ ]:
my_mat2[0,-1] = 100 # Assigning only a single unit
my_mat2

array([[ 11,  12,  13, 100],
       [ 14,  15,  16,  22],
       [ 17,  18,  19,  23]])

In [72]:
my_mat2[0] = 24 # assigning a single value to whole row
my_mat2

array([[24, 24, 24, 24],
       [14, 15, 16, 22],
       [17, 18, 19, 23]])

In [76]:
demo_lst = [1,2,3,4]
my_mat2[2] = demo_lst
my_mat2 # assigning a whole new array to the [2] of the matrix

array([[24, 24, 24, 24],
       [14, 15, 16, 22],
       [ 1,  2,  3,  4]])

#### Element wise Properties

In [ ]:
arr1 = np.array([7,8,9])
arr2 = np.array([[1,2,3],[4,5,6]])

array([[ 7, 16, 27],
       [28, 40, 54]])

In [ ]:
arr1 * 2 #scaler multiplication

array([14, 16, 18])

In [80]:
arr2 + 2 # adding 2 to each element in arr2

array([[3, 4, 5],
       [6, 7, 8]])

In [82]:
arr1  * arr2[1]  # mult of matrix with element of arr[1]

array([28, 40, 54])

#### Types of Data , Numpy supports and mostly used :  int, float, string, bool, complex

In [84]:
arr2 = np.array([[1,2,3],[4,5,6]],dtype=np.float16)
arr2

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float16)

In [86]:
arr2 = np.array([[1,2,0],[4,5,6]],dtype=np.bool)
arr2

array([[ True,  True, False],
       [ True,  True,  True]])

##### Built in methods to create an array 

#### arange: returns even space values within a given interval

In [88]:
np.arange(11,21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [89]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# using step size

np.arange(0,15,2) # step size is 2

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [91]:
# to create an array of 0s

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [92]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### Line space = returns evenly spaced numbers over a specified interval

In [94]:
np.linspace(0,100,20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

### Eye

In [96]:
np.eye(3) # to create an identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Attributes and methods of array