* finding average flat prices in a district by having city flat prices using lists 

In [9]:
flat_prices = [33.4,43,37,45,50]
total = 0
for price in flat_prices:
    total += price
# print(total)
average_price = total / len(flat_prices)

print(average_price)

41.68


* finding average flat prices in a district by having city flat prices using NUMPY

In [5]:
import numpy as np

In [8]:
flat_prices = np.array([33.4,43,37,45,50])

average_price = np.mean(flat_prices)
print(average_price)

41.68


## Array creation methods

* One dimansional Array

In [10]:
arr_one = np.array([1,2,3,4,5])
print(arr_one)

[1 2 3 4 5]


* Two Dimensional Array also known as matrix

In [13]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


* multi-dimensional array like 3d,4d,5d

In [14]:
array_3d = [
    [ [1, 2], [3, 4] ],
    [ [5, 6], [7, 8] ],
    [ [9, 10], [11, 12] ]
]
print(array_3d)


[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]


* Way to convert a list into a array in numpy

In [17]:
names = ['aditya','amol','rohan','mohit']
arr = np.array(names)
print(f"this is a list , which is slow: {names}")
print(f'this is a numpy array, which is fast and memory efficient: {arr}')

this is a list , which is slow: ['aditya', 'amol', 'rohan', 'mohit']
this is a numpy array, which is fast and memory efficient: ['aditya' 'amol' 'rohan' 'mohit']


* Creating an array with default values

* 1st way: np.zeros can be used to create an array with 0 as values

* where the zeros() method takes the shape of the array e.g. 2 or 2,3 i.e. total 6 elements

In [20]:
zeros_arr = np.zeros(4)
print(zeros_arr)

[0. 0. 0. 0.]


* 2nd way: use of ones array to create a  default array

* Use  double parenthesis to while making a 2d or 3d matrix shaped array, e.g. ((3,4))

In [22]:
ones_arr = np.ones((2,3))
print(ones_arr)

[[1. 1. 1.]
 [1. 1. 1.]]


* 3rd way:  use of full() method to fill any desired value to create an array

* Here below, 1st parameter is the shape and 2nd is the desired value to be filled

In [27]:
custom_arr = np.full((2,3),12)
print(custom_arr)

[[12 12 12]
 [12 12 12]]


* When creating a sequnce of numbers in an array we use
* arange(start,stop,step) which returns an array

In [36]:
even_arr = np.arange(2,11,2)
print(even_arr)

[ 2  4  6  8 10]


* gets neagtive numbers with step size of 2 from -11 to 0

In [43]:
negative_arr = np.arange(-11,0,2) 
print(negative_arr)

[-11  -9  -7  -5  -3  -1]


* Way to create an identity matrix , we get 1's in the diagonal 

In [44]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
